[package]
name = "snaq-lite-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "snaq-lite"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
snaq-lite-lang = { path = "../snaq-lite-lang" }
