[package]
name = "snaq-lite-lang"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[build-dependencies]
lalrpop = "0.21"

[dependencies]
lalrpop-util = { version = "0.21", features = ["lexer"] }
salsa = { version = "0.26.0", features = ["inventory"] }
